//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTheWeakestRival.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFTheWeakestRival.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an image.
        /// </summary>
        public static string btnChooseImage {
            get {
                return ResourceManager.GetString("btnChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an image.
        /// </summary>
        public static string btnImageChooser {
            get {
                return ResourceManager.GetString("btnImageChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #cb102c.
        /// </summary>
        public static string colorLogin {
            get {
                return ResourceManager.GetString("colorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email@example.com.
        /// </summary>
        public static string emailPlaceholder {
            get {
                return ResourceManager.GetString("emailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already registered.
        /// </summary>
        public static string errorEmailExists {
            get {
                return ResourceManager.GetString("errorEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or password incorrects.
        /// </summary>
        public static string errorInvalidateCredentials {
            get {
                return ResourceManager.GetString("errorInvalidateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email does not have the necessary structure.
        /// </summary>
        public static string errorInvalidEmail {
            get {
                return ResourceManager.GetString("errorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords don&apos;t match.
        /// </summary>
        public static string errorMatchingPasswords {
            get {
                return ResourceManager.GetString("errorMatchingPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fields were missing to fill out.
        /// </summary>
        public static string errorMisingFields {
            get {
                return ResourceManager.GetString("errorMisingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least 9 characters, one uppercase letter, and a symbol..
        /// </summary>
        public static string errorPasswordStructure {
            get {
                return ResourceManager.GetString("errorPasswordStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username already exists.
        /// </summary>
        public static string errorUsernameExists {
            get {
                return ResourceManager.GetString("errorUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username should not have spaces.
        /// </summary>
        public static string errorUsernameWithoutSpaces {
            get {
                return ResourceManager.GetString("errorUsernameWithoutSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error on the registration.
        /// </summary>
        public static string generalRegistError {
            get {
                return ResourceManager.GetString("generalRegistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Properties/Images/logo_en.png.
        /// </summary>
        public static string imageLogo {
            get {
                return ResourceManager.GetString("imageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /Properties/Images/logo_en.png.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have account?.
        /// </summary>
        public static string notAccount {
            get {
                return ResourceManager.GetString("notAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password.
        /// </summary>
        public static string passwordPlaceHolder {
            get {
                return ResourceManager.GetString("passwordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string playAsGuest {
            get {
                return ResourceManager.GetString("playAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        public static string regist {
            get {
                return ResourceManager.GetString("regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string registerDisplayName {
            get {
                return ResourceManager.GetString("registerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registratioon error.
        /// </summary>
        public static string registerError {
            get {
                return ResourceManager.GetString("registerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        public static string registerTitle {
            get {
                return ResourceManager.GetString("registerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        public static string registHeader {
            get {
                return ResourceManager.GetString("registHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The registration has been success.
        /// </summary>
        public static string registSucces {
            get {
                return ResourceManager.GetString("registSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to The weakest rival.
        /// </summary>
        public static string succesLoginMessage {
            get {
                return ResourceManager.GetString("succesLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your profile picture.
        /// </summary>
        public static string tittleImageSelector {
            get {
                return ResourceManager.GetString("tittleImageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
    }
}
